title: Vihang Patil
owner: Vihang Patil
email: vihang.patil@usi.ch
description: Master Student in Artificial Intelligence | Actively looking for PhD positions in Machine Learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username: "vihangp"
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
